### In Elevator 1 pressed button to 5 flor
http://localhost:8081/rest/v1/requestInsideElevator/1/5
###Request to 7 floor
http://localhost:8081/rest/v1/requestElevator/7/up
###Request to 9 floor
http://localhost:8081/rest/v1/requestElevator/9/down
###